"""DHCP server control — wraps Kirby's dhcpsrv.exe (http://www.dhcpserver.de/).

Generates a valid dhcpsrv.ini (per dhcpserver.de/cms/ini_file_reference/) and
spawns dhcpsrv.exe with `-runapp -ini <path>` as a child process.

The dhcpsrv binary is bundled with the app (see --add-data in build.bat).
When running from the PyInstaller bundle, sys._MEIPASS points at the
extraction directory containing `dhcpsrv/dhcpsrv.exe`. When running from
source, we look for `vendor/dhcpsrv/dhcpsrv.exe` in the project.
"""
from __future__ import annotations

import os
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Optional

import psutil

from . import firewall
from . import dhcp_log
from .config import CONFIG_PATH, DhcpConfig
from .validate import validate_dhcp_range

CREATE_NO_WINDOW = 0x08000000

_proc: Optional[subprocess.Popen] = None
_lock = threading.Lock()


def bundled_dhcpsrv_path() -> Optional[str]:
    """Locate the bundled dhcpsrv.exe. Returns None if it can't be found."""
    candidates: list[Path] = []
    # PyInstaller onefile/onedir extraction dir
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        candidates.append(Path(meipass) / "dhcpsrv" / "dhcpsrv.exe")
    # Running from source
    here = Path(__file__).resolve().parent.parent
    candidates.append(here / "vendor" / "dhcpsrv" / "dhcpsrv.exe")
    for p in candidates:
        if p.is_file():
            return str(p)
    return None


def effective_exe_path(cfg: DhcpConfig) -> Optional[str]:
    """Return the best dhcpsrv.exe path to use: the user's configured path
    if it exists, else the bundled copy, else None.
    """
    if cfg.exe_path and Path(cfg.exe_path).is_file():
        return cfg.exe_path
    return bundled_dhcpsrv_path()


def is_running() -> bool:
    with _lock:
        return _proc is not None and _proc.poll() is None


def exe_exists(cfg: DhcpConfig) -> bool:
    return effective_exe_path(cfg) is not None


def _runtime_dir() -> Path:
    """Where dhcpsrv.ini and dhcpsrv.log live — always writable."""
    d = CONFIG_PATH.parent
    d.mkdir(parents=True, exist_ok=True)
    return d


def _ini_path(cfg: DhcpConfig) -> Path:
    return _runtime_dir() / "dhcpsrv.ini"


def _trace_path(cfg: DhcpConfig) -> Path:
    return _runtime_dir() / "dhcpsrv.log"


def _stderr_path(cfg: DhcpConfig) -> Path:
    return _runtime_dir() / "dhcpsrv-stderr.log"


def _kill_orphans() -> int:
    """Kill any lingering dhcpsrv.exe from a previous crashed session.
    Returns number of processes killed."""
    killed = 0
    for proc in psutil.process_iter(["name", "pid"]):
        try:
            if (proc.info.get("name") or "").lower() == "dhcpsrv.exe":
                proc.terminate()
                try:
                    proc.wait(timeout=2)
                except psutil.TimeoutExpired:
                    proc.kill()
                killed += 1
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            pass
    return killed


def _build_ini(cfg: DhcpConfig, end_octet: int) -> str:
    """Build the dhcpsrv.ini content per official reference.

    Pools live in [SETTINGS] as IPPOOL_x=start-endOctet. Client options go in
    [GENERAL]. `_0`..`_9` suffixes are indexed option rows.
    """
    trace = str(_trace_path(cfg)).replace("\\", "/")
    lines: list[str] = []
    lines.append("; Generated by NIC Switcher — do not edit by hand.")
    lines.append("[SETTINGS]")
    lines.append(f"IPBIND_1={cfg.bind_ip}")
    lines.append(f"IPPOOL_1={cfg.range_start}-{end_octet}")
    lines.append("AssociateBindsToPools=1")
    lines.append("Trace=1")
    lines.append(f"TraceFile={trace}")
    lines.append("")
    lines.append("[GENERAL]")
    lines.append(f"SUBNETMASK={cfg.subnet_mask}")
    if cfg.gateway:
        lines.append(f"ROUTER_0={cfg.gateway}")
    if cfg.dns:
        # split on comma/space so "8.8.8.8, 1.1.1.1" works
        parts = [x.strip() for x in cfg.dns.replace(",", " ").split() if x.strip()]
        for idx, dns in enumerate(parts[:10]):
            lines.append(f"DNS_{idx}={dns}")
    lines.append(f"LEASETIME={max(60, int(cfg.lease_seconds))}")
    lines.append("NODETYPE=8")
    lines.append("")
    return "\n".join(lines)


def _write_ini(cfg: DhcpConfig, end_octet: int) -> Path:
    path = _ini_path(cfg)
    # Use utf-8 — safe for all ASCII content, won't fail on odd characters.
    path.write_text(_build_ini(cfg, end_octet), encoding="utf-8")
    return path


def start(cfg: DhcpConfig) -> tuple[bool, str]:
    """Synchronous start. Call from a worker thread — the firewall netsh calls
    and the 1.2s probe wait will block for several seconds total.
    """
    global _proc
    if is_running():
        return True, "Already running"
    exe = effective_exe_path(cfg)
    if not exe:
        return False, "dhcpsrv.exe not found (bundled copy missing)"

    ok, err, end_octet = validate_dhcp_range(
        cfg.bind_ip, cfg.range_start, cfg.range_end, cfg.subnet_mask
    )
    if not ok or end_octet is None:
        return False, err or "Invalid DHCP configuration"

    # Recover from any orphan dhcpsrv from a previous crash — otherwise port 67
    # is held and the new process exits immediately.
    killed = _kill_orphans()

    try:
        ini = _write_ini(cfg, end_octet)
    except OSError as e:
        return False, f"Could not write dhcpsrv.ini: {e}"

    # NOTE: firewall rules are NOT added here — netsh is slow (3-5s per call)
    # on locked-down machines and would block the whole start path. The Configure
    # dialog handles firewall rules async, and main.py fires a background
    # ensure_dhcp_rules once at app startup. If dhcpsrv can't receive packets
    # the user can hit "Apply now" in the Configure dialog.

    stderr_path = _stderr_path(cfg)
    try:
        stderr_fh = open(stderr_path, "w", encoding="utf-8")
    except OSError:
        stderr_fh = subprocess.DEVNULL

    try:
        with _lock:
            _proc = subprocess.Popen(
                [exe, "-runapp", "-ini", str(ini)],
                cwd=str(Path(exe).parent),
                creationflags=CREATE_NO_WINDOW,
                stdout=stderr_fh,
                stderr=stderr_fh,
                stdin=subprocess.DEVNULL,
            )
        # Give it a moment to fail fast (bad bind, port taken, etc.)
        try:
            rc = _proc.wait(timeout=1.2)
        except subprocess.TimeoutExpired:
            rc = None

        if rc is not None:
            # Died immediately — read dhcpsrv.log for the real reason.
            reason = _read_exit_reason(cfg, stderr_path)
            with _lock:
                _proc = None
            try:
                if stderr_fh not in (subprocess.DEVNULL,):
                    stderr_fh.close()
            except Exception:
                pass
            return False, (
                f"dhcpsrv.exe exited immediately (code {rc}). {reason}"
            )

        prefix = f"Recovered {killed} orphan(s). " if killed else ""
        return True, (
            f"{prefix}DHCP serving {cfg.range_start} – {cfg.range_end} on {cfg.bind_ip}"
        )
    except Exception as e:
        with _lock:
            _proc = None
        try:
            if stderr_fh not in (subprocess.DEVNULL,):
                stderr_fh.close()
        except Exception:
            pass
        return False, f"Failed to start: {e}"


def _read_exit_reason(cfg: DhcpConfig, stderr_path: Path) -> str:
    """Gather a short human-readable exit reason from the log files."""
    hints: list[str] = []
    log = _trace_path(cfg)
    try:
        if log.is_file():
            # last ~40 lines
            lines = log.read_text(encoding="utf-8", errors="ignore").splitlines()
            tail = [ln for ln in lines[-40:] if ln.strip()]
            if tail:
                last = tail[-1]
                hints.append(last[:200])
    except Exception:
        pass
    try:
        if stderr_path.is_file():
            text = stderr_path.read_text(encoding="utf-8", errors="ignore").strip()
            if text:
                hints.append(text.splitlines()[-1][:200])
    except Exception:
        pass
    if not hints:
        return f"Check {log} for details."
    return " | ".join(hints) + f"  (full log: {log})"


def lease_snapshot(max_events: int = 25) -> dhcp_log.LeaseSnapshot:
    """Pull the latest lease activity from the running server's trace file."""
    log = _trace_path(DhcpConfig())  # path only depends on runtime dir, not cfg
    events = dhcp_log.tail_events(log, max_events=max_events)
    return dhcp_log.summarize(events)


def trace_log_path() -> Path:
    return _trace_path(DhcpConfig())


def stop() -> tuple[bool, str]:
    global _proc
    with _lock:
        proc = _proc
    if proc is None or proc.poll() is not None:
        with _lock:
            _proc = None
        return True, "Not running"
    try:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=2)
        with _lock:
            _proc = None
        return True, "DHCP server stopped"
    except Exception as e:
        return False, f"Stop failed: {e}"
